version: "3.7"
services:
  app:
    build:
      context: ../..
      dockerfile: config/docker/app/Dockerfile
    container_name: tetris-app
    environment:
      - NODE_ENV=production
    ports:
      - 81:9000
    dns:
      - 8.8.8.8
    volumes:
      - type: volume
        source: public
        target: /usr/src/app

  nginx:
    build:
      context: ../..
      dockerfile: config/docker/nginx/Dockerfile
    container_name: tetris-nginx
    ports:
      - 80:80
    dns:
      - 8.8.8.8
    volumes:
      - type: volume
        source: public
        target: /var/www/app
    depends_on:
      - app

volumes:
  public:
